### ISSUE TITLE
[BUG] Cannot find symbol for Custom app react symbols 

### ISSUE THREAD

**Issue by ReaperCalli** [JulienMaille/dribbblish-dynamic-theme#27]
Im getting the cannot find symbol error when applying the theme which makes spotify unusable.

**Screenshots**
![image](https://user-images.githubusercontent.com/59681368/126899314-7c6a270c-502f-471b-8a48-1c0b70abbddc.png)
![image](https://user-images.githubusercontent.com/59681368/126899336-a1ff2360-2c4d-47bd-9018-7b27a5b46f9b.png)

**Desktop:**
 - OS: Windows 10

The command for devtools doesn't work idk why

**Comment by HybridRaven** [comment]
It happens with spotify  v1.63...

Install older version (1.62) and block auto update and you will be good. All works fine with spotify 1.62 and spicetify-cli v2.50

**Comment by ReaperCalli** [comment]
I see I'll do that thank you.
